### ISSUE TITLE
Alignment of source code to staging instance new endpoints

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#102]
In accordance with the issue [Update of Staging Instance URLs](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1104), which indicates that the staging endpoint has changed for both the UI and the API, it is necessary to review the product URLs to ensure compatibility with this new configuration.

**Comment by fabiovinci** [comment]
The URL of the staging instance also needs to be changed in the Validator menu.

![image](https://github.com/user-attachments/assets/48d3da37-a233-4f72-a330-17473500f26c)

**Comment by veronicamonaco** [comment]
For the issue discussed yesterday regarding the wrong mapping in the test suites in the test report page, I think the error is caused by a wrong value of the property serverDirectURL in the config.js file (it should be https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator-staging/v2/). As it regards properties present in this PR, let me know if you proceed to make this change or I can do it.
<img width="584" alt="image" src="https://github.com/user-attachments/assets/3ffebd84-aa6b-458f-a79b-1af69c5f3c17">
